### ISSUE TITLE
Better map

### ISSUE THREAD

**Issue by Westernbird** [gegy1000/EarthBiomemap#1]
For some reason Sync doesn't work (I'm newbie in that :S), and my changes aren't being displayed.
Here are parts of map which I improved. Hopefully, you will accept them.
![biomemap_x4y0](https://cloud.githubusercontent.com/assets/16960976/14151612/9da8f1fa-f6d0-11e5-8b10-7ff6feb6ef9d.png) - x4y0
![biomemap_x4y1](https://cloud.githubusercontent.com/assets/16960976/14151616/a0045e94-f6d0-11e5-8023-012165220314.png) - x4y1
![biomemap_x5y0](https://cloud.githubusercontent.com/assets/16960976/14151622/a2d7eb22-f6d0-11e5-86bf-b1fe668eafbd.png) - x5y0

Sincerely,
Tom Riddle.

**Comment by gegy1000** [comment]
Thanks for your contribution! I'll implement them when I get home in 4 days. Your problem is that you haven't created a fork of this repository, so you don't have access to it.

**Comment by Westernbird** [comment]
Thanks for replying.
I guess you need to revamp biomes overall.
My suggestion is to make various biomes like Arctic Tundra, Larch Taiga, Semi-desert, etc. with many variants, like Plains, Forest, Hills, etc.
The suggestion I described can be seen in Lord of the Rings mod, there the map is split to such biomes.

**Comment by gegy1000** [comment]
Thanks for the suggestion, I will take a look at the LotR mod. :)

**Comment by Westernbird** [comment]
How is progress?

**Comment by gegy1000** [comment]
Oh, sorry, I completely forgot about this! I'll merge your changes now. :)

**Comment by gegy1000** [comment]
Hey, would you be able to fix x3y0 and x5y0? You didn't update them after updating the other tiles, which creates these borders. http://i.imgur.com/90g1zIN.png :)

**Comment by gegy1000** [comment]
I'm going to make the mod work with Biomes O' Plenty biomes, the biomemap will be redone.
